### PR TITLE
fix: image resizes, and fixes bootstrap code

### PR DESCRIPTION
**Pull request by Meng-Heng**

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
Query: are the images scaled down from the original or rescaled multiple times? Because they look a little blurry, which I was not expecting. It might be better to work from scalable images and export than to rescale a PNG

**Comment by Meng-Heng** [comment]
@mcdurdin, I just tried compressing them again but still very blurry. I was doing only one compression.

sil-logo-andika-v
sil-logo-tai-heritage-pr
sil-logo-abbysinic
sil-logo-annapurn

I don't quite know how to use scalable images and then export.
sil-logo-abbysinica
I downloaded the logos then convert through a site to 5 KB straight away. Is there another quick and easy way?

**Comment by mcdurdin** [comment]
SIL Glyph Logo Color - Abbysinica 500x270
SIL Glyph Logo Color - Andika v1 500x270
SIL Glyph Logo Color - Andika v2 500x270
SIL Glyph Logo Color - Annapurna 500x270
SIL Glyph Logo Color - Tai Heritage Pro 500x270

OK, I rescaled them using Paint.NET, seems to be working well. (Trimmed borders off to match what you have here.) Saved as .png. Also saved to Keyman Share Drive

**Pull request merged**
